services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BASE_PATH=${BASE_PATH}
      - POKEMON_TCG_API_KEY=${POKEMON_TCG_API_KEY}
